repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.0.1
  hooks:
    - id: check-added-large-files
    - id: check-case-conflict
    - id: check-merge-conflict
    - id: check-yaml
    - id: detect-aws-credentials
      args: [--allow-missing-credentials]
    - id: end-of-file-fixer
    - id: trailing-whitespace
    - id: mixed-line-ending
- repo: local
  hooks:
  - id: scan-secrets
    name: Scan secrets
    entry: ./scripts/githooks/scan-secrets.sh
    args: ["check=staged-changes"]
    language: script
    pass_filenames: false
- repo: local
  hooks:
  - id: check-file-format
    name: Check file format
    entry: ./scripts/githooks/check-file-format.sh
    args: ["check=staged-changes"]
    language: script
    pass_filenames: false
- repo: local
  hooks:
  - id: check-markdown-format
    name: Check Markdown format
    entry: ./scripts/githooks/check-markdown-format.sh
    args: ["check=staged-changes"]
    language: script
    pass_filenames: false
- repo: local
  hooks:
  - id: check-english-usage
    name: Check English usage
    entry: ./scripts/githooks/check-english-usage.sh
    args: ["check=staged-changes"]
    language: script
    pass_filenames: false
- repo: local
  hooks:
  - id: lint-terraform
    name: Lint Terraform
    entry: ./scripts/githooks/check-terraform-format.sh
    language: script
    pass_filenames: false
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.9.7
  hooks:
    - id: ruff
      args: [ --fix ]
    - id: ruff-format
- repo: https://github.com/RobertCraigie/pyright-python
  rev: v1.1.394
  hooks:
  - id: pyright
- repo: https://github.com/milin/giticket
  rev: v1.3
  hooks:
    - id: giticket
      args: [ '--regex=(?i)ELID-\d+', '--format=[{ticket}] {commit_msg}', '--mode=regex_match' ]
      stages: [commit-msg]
