version: "3.8"
services:
  localstack:
    image: localstack/localstack
    container_name: localstack_ieds
    ports:
      - "4566:4566"  # Main API Gateway
      - "4571-4599:4571-4599"  # Service-specific ports (optional range)
    environment:
      - SERVICES=${SERVICES}
      - DEBUG=${DEBUG}
      - DATA_DIR=${DATA_DIR}
      - HOSTNAME=${HOSTNAME}
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
      - DOCKER_HOST=${DOCKER_HOST}
      - LOCALSTACK_API_KEY=${LOCALSTACK_API_KEY}
      - USE_SSL=${USE_SSL}
      - EXTRA_CORS_ALLOWED_HEADERS=${EXTRA_CORS_ALLOWED_HEADERS}
      - EXTRA_CORS_ALLOWED_ORIGINS=${EXTRA_CORS_ALLOWED_ORIGINS}
    volumes:
      - "./localstack_data:/var/lib/localstack"  # Persist data in a local volume
