name: "Auto Deploy to test"

on:
  workflow_call:
    inputs:
      ref:
        required: true
        type: string

concurrency:
  group: terraform-deploy-test
  cancel-in-progress: false

permissions:
  contents: read
  id-token: write
  actions: read

jobs:
  metadata:
    name: "Resolve metadata from triggering run"
    runs-on: ubuntu-latest
    # keep your guard if you want, but it’s not needed with workflow_call
    outputs:
      terraform_version: ${{ steps.vars.outputs.terraform_version }}
      tag: ${{ steps.tag.outputs.name }}
    steps:
      - name: "Checkout exact commit from CI/CD publish"
        uses: actions/checkout@v5
        with:
          ref: ${{ inputs.ref }}

      - name: "Set CI/CD variables"
        id: vars
        run: |
          echo "terraform_version=$(grep '^terraform' .tool-versions | cut -f2 -d' ')" >> $GITHUB_OUTPUT

      - name: "Resolve the dev-* tag for this commit"
        id: tag
        run: |
          git fetch --tags --force
          SHA="${{ inputs.ref }}"
          TAG=$(git tag --points-at "$SHA" | grep '^dev-' | head -n1 || true)
          if [ -z "$TAG" ]; then
            echo "No dev-* tag found on $SHA" >&2
            exit 1
          fi
          echo "name=$TAG" >> $GITHUB_OUTPUT
          echo "Resolved tag: $TAG"

  deploy:
    name: "Deploy to TEST (approval required)"
    runs-on: ubuntu-latest
    needs: [metadata]
    environment: test
    permissions:
      id-token: write
      contents: read
    steps:
      - name: "Checkout same commit"
        uses: actions/checkout@v5
        with:
          ref: ${{ inputs.ref }}

      - name: "Setup Terraform"
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ needs.metadata.outputs.terraform_version }}

      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: "Configure AWS Credentials"
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/service-roles/github-actions-api-deployment-role
          aws-region: eu-west-2

      - name: "Build lambda artefact (rebuild in TEST)"
        run: |
          make dependencies install-python
          make build

      - name: "Terraform Apply (TEST)"
        env:
          ENVIRONMENT: test
          WORKSPACE: "default"
          TF_VAR_API_CA_CERT: ${{ secrets.API_CA_CERT }}
          TF_VAR_API_CLIENT_CERT: ${{ secrets.API_CLIENT_CERT }}
          TF_VAR_API_PRIVATE_KEY_CERT: ${{ secrets.API_PRIVATE_KEY_CERT }}
          TF_VAR_SPLUNK_HEC_TOKEN: ${{ secrets.SPLUNK_HEC_TOKEN }}
          TF_VAR_SPLUNK_HEC_ENDPOINT: ${{ secrets.SPLUNK_HEC_ENDPOINT }}
        run: |
          mkdir -p ./build
          echo "Deploying tag: ${{ needs.metadata.outputs.tag }}"
          echo "Running: make terraform env=$ENVIRONMENT workspace=$WORKSPACE stack=networking tf-command=apply"
          make terraform env=$ENVIRONMENT stack=networking tf-command=apply workspace=$WORKSPACE
          echo "Running: make terraform env=$ENVIRONMENT workspace=$WORKSPACE stack=api-layer tf-command=apply"
          make terraform env=$ENVIRONMENT stack=api-layer tf-command=apply workspace=$WORKSPACE
        working-directory: ./infrastructure
