name: E2E Regression Tests

on:
  workflow_call:
    inputs:
      ENVIRONMENT:
        required: true
        type: string
      VERSION_NUMBER:
        required: true
        type: string
    secrets:
      AWS_ACCOUNT_ID:
        required: true

jobs:
  regression-tests:
    if: ${{ inputs.ENVIRONMENT != 'prod' }}
    permissions:
      id-token: write
      contents: read
      issues: write
      pull-requests: write
    uses: NHSDigital/eligibility-signposting-api-regression-tests/.github/workflows/regression_tests.yml@main
    secrets: inherit
    with:
      environment: ${{ inputs.ENVIRONMENT }}
      tags: "@regression"
      github_tag: ${{ inputs.VERSION_NUMBER }}
