name: E2E Regression Tests

on:
  workflow_call:
    inputs:
      ENVIRONMENT:
        required: true
        type: string
      VERSION_NUMBER:
        required: true
        type: string

jobs:
  regression-tests:
    if: ${{ (inputs.ENVIRONMENT != 'prod') && (inputs.ENVIRONMENT != 'preprod') }}
    uses: NHSDigital/eligibility-signposting-api-regression-tests/.github/workflows/regression_tests.yml@main
    with:
      environment: ${{ inputs.ENVIRONMENT }}
      tags: "@regression"
      github_tag: ${{ inputs.VERSION_NUMBER }}
