name: Run Regression Tests

on:
  workflow_call:
    inputs:
      ENVIRONMENT:
        required: true
        type: string
      VERSION_NUMBER:
        required: true
        type: string
      REGRESSION_TESTS_PEM:
        type: string
      PRODUCT:
        type: string

jobs:
  run_regression_tests:
    runs-on: ubuntu-22.04
    environment: ${{ inputs.ENVIRONMENT }}
    permissions:
      id-token: write
      contents: write

    steps:
#      - name: Generate a token to authenticate regression testing
#        id: generate-token
#        uses: actions/create-github-app-token@v1
#        with:
#          app-id: ${{ vars.REGRESSION_TESTS_APP_ID }}
#          private-key: ${{ secrets.REGRESSION_TESTS_PEM }}
#          owner: "NHSDigital"
#          repositories: "eligibility-signposting-api-regression-tests"

      - name: Run Regression Testing
        working-directory: scripts
        if: ${{ (inputs.ENVIRONMENT != 'prod') && (inputs.ENVIRONMENT != 'ref') }}
        env:
          TARGET_ENVIRONMENT: ${{ inputs.ENVIRONMENT }}
          VERSION_NUMBER: ${{ inputs.VERSION_NUMBER }}
          GITHUB-TOKEN: ${{ secrets.GITHUB_TOKEN }}
#          GITHUB-TOKEN: ${{ steps.generate-token.outputs.token }}
        run: |
              poetry install
              echo Running regression tests in the "$TARGET_ENVIRONMENT" environment
              poetry run python run_regression_tests.py \
                --env="$TARGET_ENVIRONMENT" \
                --pr_label="$VERSION_NUMBER" \
                --token="$GITHUB-TOKEN"
