name: Run Regression Tests

on:
  workflow_call:
    inputs:
      ENVIRONMENT:
        required: true
        type: string
      VERSION_NUMBER:
        required: true
        type: string
      PRODUCT:
        type: string

jobs:
  run_regression_tests:
    runs-on: ubuntu-22.04
    environment: ${{ inputs.ENVIRONMENT }}
    permissions:
      id-token: write
      contents: write

    steps:
      - name: Checkout local github actions
        uses: actions/checkout@v5
        with:
          ref: ${{ env.BRANCH_NAME }}
          fetch-depth: 0

      - name: Cache asdf
        uses: actions/cache@0400d5f644dc74513175e3cd8d07132dd4860809
        with:
          path: |
            ~/.asdf
          key: ${{ runner.os }}-asdf-${{ hashFiles('**/.tool-versions') }}
          restore-keys: |
            ${{ runner.os }}-asdf-

      - name: Install asdf dependencies in .tool-versions
        uses: asdf-vm/actions/install@1902764435ca0dd2f3388eea723a4f92a4eb8302
        with:
          asdf_branch: v0.15.0
        env:
          PYTHON_CONFIGURE_OPTS: --enable-shared

      - name: setup venv
        uses: actions/checkout@v5
      - uses: actions/setup-python@v6
        with:
#          python-version: '3.13.5'
          cache: 'poetry' # caching poetry dependencies
      - run: poetry install

      - name: Run Regression Testing
        working-directory: scripts
        if: ${{ (inputs.ENVIRONMENT != 'prod') && (inputs.ENVIRONMENT != 'ref') }}
        env:
          TARGET_ENVIRONMENT: ${{ inputs.ENVIRONMENT }}
          VERSION_NUMBER: ${{ inputs.VERSION_NUMBER }}
          TESTS_TOKEN: ${{ secrets.REGRESSION_TESTS_PAT }}
        # GITHUB_TOKEN: ${{ steps.generate-token.outputs.token }}
        run: |
          echo Running regression tests in the "$TARGET_ENVIRONMENT" environment.
          poetry run python run_regression_tests.py \
          --env="$TARGET_ENVIRONMENT" \
          --token="$TESTS_TOKEN" \
          --regression_test_repo_tag "$VERSION_NUMBER"
