name: "Test tag & release"

on:
  workflow_dispatch:
    inputs:
      ref:
        description: "Branch/Tag/SHA to deploy to test"
        required: true
        default: "dev-20250916094908"
      release_type:
        description: "Version bump type (use 'rc' to keep the same base and just increment RC)"
        required: true
        default: "rc"
        type: choice
        options:
          - rc
          - patch
          - minor
          - major

jobs:
  metadata:
    name: "Set CI/CD metadata"
    runs-on: ubuntu-latest
    timeout-minutes: 10
    outputs:
      build_datetime: ${{ steps.variables.outputs.build_datetime }}
      build_timestamp: ${{ steps.variables.outputs.build_timestamp }}
      build_epoch: ${{ steps.variables.outputs.build_epoch }}
      nodejs_version: ${{ steps.variables.outputs.nodejs_version }}
      python_version: ${{ steps.variables.outputs.python_version }}
      terraform_version: ${{ steps.variables.outputs.terraform_version }}
      version: ${{ steps.variables.outputs.version }}
      tag: ${{ steps.variables.outputs.tag }}
      ref: ${{ github.event.inputs.ref }}
    steps:
      - name: "Checkout ref"
        uses: actions/checkout@v5
        with:
          ref: ${{ github.event.inputs.ref }}

      - name: "Set CI/CD variables"
        id: variables
        run: |
          datetime=$(date -u +'%Y-%m-%dT%H:%M:%S%z')
          echo "build_datetime=$datetime" >> $GITHUB_OUTPUT
          echo "build_timestamp=$(date --date=$datetime -u +'%Y%m%d%H%M%S')" >> $GITHUB_OUTPUT
          echo "build_epoch=$(date --date=$datetime -u +'%s')" >> $GITHUB_OUTPUT
          echo "nodejs_version=$(grep '^nodejs' .tool-versions | cut -f2 -d' ')" >> $GITHUB_OUTPUT
          echo "python_version=$(grep '^python' .tool-versions | cut -f2 -d' ')" >> $GITHUB_OUTPUT
          echo "terraform_version=$(grep '^terraform' .tool-versions | cut -f2 -d' ')" >> $GITHUB_OUTPUT
          echo "version=$(head -n 1 .version 2> /dev/null || echo unknown)" >> $GITHUB_OUTPUT
          echo "tag=${{ github.event.inputs.ref }}" >> $GITHUB_OUTPUT

      - name: "List variables"
        run: |
          export BUILD_DATETIME="${{ steps.variables.outputs.build_datetime }}"
          export BUILD_TIMESTAMP="${{ steps.variables.outputs.build_timestamp }}"
          export BUILD_EPOCH="${{ steps.variables.outputs.build_epoch }}"
          export NODEJS_VERSION="${{ steps.variables.outputs.nodejs_version }}"
          export PYTHON_VERSION="${{ steps.variables.outputs.python_version }}"
          export TERRAFORM_VERSION="${{ steps.variables.outputs.terraform_version }}"
          export VERSION="${{ steps.variables.outputs.version }}"
          export TAG="${{ steps.variables.outputs.tag }}"
          make list-variables

  test:
    name: "Test tag and release"
    runs-on: ubuntu-latest
    needs: [metadata]
    environment: test
    timeout-minutes: 10080
    permissions:
      id-token: write
      contents: write
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v5
        with:
          ref: ${{ needs.metadata.outputs.ref }}

      - name: "Manage Release"
        env:
          ENVIRONMENT: test
          REF: ${{ needs.metadata.outputs.ref }}
          INPUT_RELEASE_TYPE: ${{ github.event.inputs.release_type }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
        run: python scripts/seed_users/tag_and_release.py
